<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <!--
      Adding NoWarn to remove build warnings
      NU1507: Warning when there are multiple package sources when using CPM with no source mapping
      NETSDK1201: Warning that specifying RID won't create self containing app
      PRI257: Ignore default language (en) not being one of the included resources (eg en-us, en-uk)
    -->
    <NoWarn>$(NoWarn);NU1507;NETSDK1201;PRI257</NoWarn>

    <!-- Central Dynamic Application Branding -->
    <AppName Condition="'$(AppName)' == ''">Sefirah AI</AppName>
    <AppTitle Condition="'$(AppTitle)' == ''">Sefirah AI</AppTitle>
    <AppDescription Condition="'$(AppDescription)' == ''">Sefirah AI: Seamless cross-device intelligence.</AppDescription>
    <AppId Condition="'$(AppId)' == ''">vthonte.Sefirah-AI</AppId>
  </PropertyGroup>
</Project>
